// Bring these types to reducers
export const AUTHENTICATE = "AUTHENTICATE";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";
export const GET_WAVEFORM_SUCCESS = "GET_WAVEFORM_SUCCESS";
export const GET_WAVEFORM_FAILURE = "GET_WAVEFORM_FAILURE";
export const DELETE_WAVEFORM_SUCCESS = "DELETE_WAVEFORM_SUCCESS";
export const DELETE_WAVEFORM_FAILURE = "DELETE_WAVEFORM_FAILURE";
export const SAVE_WAVEFORM_SUCCESS = "SAVE_WAVEFORM_SUCCESS";
export const SAVE_WAVEFORM_FAILURE = "SAVE_WAVEFORM_FAILURE";
export const LOAD_SUCCESS = "LOAD_SUCCESS";
export const LOAD_FAILURE = "LOAD_FAILURE";
export const SWITCH_WAVEFORM = "SWITCH_WAVEFORM";
